export const GET_ALL_USERS = "GET_ALL_USERS";

export const EDIT_USER_FIELD = 'EDIT_USER_FIELD';

// USERS
export const USERS_REQUEST = 'USERS_REQUEST';
export const USERS_SUCCESS = 'USERS_SUCCESS';
export const USERS_FAILURE = 'USERS_FAILURE';

export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

export const USERS_ADD_REQUEST = 'USERS_ADD_REQUEST';
export const USERS_ADD_SUCCESS = 'USERS_ADD_SUCCESS';
export const USERS_ADD_FAILURE = 'USERS_ADD_FAILURE';

export const USERS_DEL_REQUEST = 'USERS_DEL_REQUEST';
export const USERS_DEL_SUCCESS = 'USERS_DEL_SUCCESS';
export const USERS_DEL_FAILURE = 'USERS_DEL_FAILURE';

export const USERS_EDIT_REQUEST = 'USERS_EDIT_REQUEST';
export const USERS_EDIT_SUCCESS = 'USERS_EDIT_SUCCESS';
export const USERS_EDIT_FAILURE = 'USERS_EDIT_FAILURE';

export const USER_TASKS_REQUEST = 'USER_TASKS_REQUEST';
export const USER_TASKS_SUCCESS = 'USER_TASKS_SUCCESS';
export const USER_TASKS_FAILURE = 'USER_TASKS_FAILURE';



// TASKS
export const TASKS_REQUEST = 'TASKS_REQUEST';
export const TASKS_SUCCESS = 'TASKS_SUCCESS';
export const TASKS_FAILURE = 'TASKS_FAILURE';

export const TASKS_ADD_REQUEST = 'TASKS_ADD_REQUEST';
export const TASKS_ADD_SUCCESS = 'TASKS_ADD_SUCCESS';
export const TASKS_ADD_FAILURE = 'TASKS_ADD_FAILURE';

export const TASKS_DEL_REQUEST = 'TASKS_DEL_REQUEST';
export const TASKS_DEL_SUCCESS = 'TASKS_DEL_SUCCESS';
export const TASKS_DEL_FAILURE = 'TASKS_DEL_FAILURE';

export const TASKS_EDIT_REQUEST = 'TASKS_EDIT_REQUEST';
export const TASKS_EDIT_SUCCESS = 'TASKS_EDIT_SUCCESS';
export const TASKS_EDIT_FAILURE = 'TASKS_EDIT_FAILURE';

export const TASKS_CHECKED_REQUEST = 'TASKS_CHECKED_REQUEST';
export const TASKS_CHECKED_SUCCESS = 'TASKS_CHECKED_SUCCESS';
export const TASKS_CHECKED_FAILURE = 'TASKS_CHECKED_FAILURE';


