export const ADD_TASK = "ADD_TASK";
export const DEL_TASK = "DEL_TASK";
export const EDITED_TASK = "EDITED_TASK";
export const CHECKED_TASK = "CHECKED_TASK";

export const GET_ALL_USERS = "GET_ALL_USERS";


export const USERS_REQUEST = 'USERS_REQUEST';
export const USERS_SUCCESS = 'USERS_SUCCESS';
export const USERS_FAILURE = 'USERS_FAILURE';

export const TASKS_REQUEST = 'TASKS_REQUEST';
export const TASKS_SUCCESS = 'TASKS_SUCCESS';
export const TASKS_FAILURE = 'TASKS_FAILURE';

export const TASKS_ADD_REQUEST = 'TASKS_ADD_REQUEST';
export const TASKS_ADD_SUCCESS = 'TASKS_ADD_SUCCESS';
export const TASKS_ADD_FAILURE = 'TASKS_ADD_FAILURE';

export const TASKS_DEL_REQUEST = 'TASKS_DEL_REQUEST';
export const TASKS_DEL_SUCCESS = 'TASKS_DEL_SUCCESS';
export const TASKS_DEL_FAILURE = 'TASKS_DEL_FAILURE';

export const TASKS_EDIT_REQUEST = 'TASKS_EDIT_REQUEST';
export const TASKS_EDIT_SUCCESS = 'TASKS_EDIT_SUCCESS';
export const TASKS_EDIT_FAILURE = 'TASKS_EDIT_FAILURE';

export const EDIT_USER_FIELD = 'EDIT_USER_FIELD';
